### PR TITLE
Removed "top" css property from .doc-left-side which fixes ticket #46.

### PR DESCRIPTION
**Pull request by Waizujin**
This is a fix to ticket #46

[Review on Reviewable](https://reviewable.io/reviews/ubirimi/ubirimi/50)

### CODE REVIEW

**Comment by w2pc** [comment]
Can you do a quick check and make sure this still works since this change earlier? https://github.com/ubirimi/ubirimi/commit/9eb14275b6f72315bd65dfaf28779d197d48206f

**Comment by Waizujin** [comment]
That changes the header section, this changes the sidebar. It doesn't seem to conflict or cause any issues I can see. However I am unsure how to make the Documentador Administration section to display. Still new to the project. 

This is what I see: http://screencast.com/t/ehjYxwclSmm

**Comment by w2pc** [comment]
Have you done a recent pull?

**Comment by Waizujin** [comment]
Yes, I pulled after you last commit which fixed the other bug I reported Issue #49. The width is 116px on mine as well, but that Documentador is still being put on 2 lines. But I believe that is a separate issue.

**Pull request merged**
